from . import maritime_port
from . import res_partner
from . import res_users
from . import maritime_notification_mixin
from . import maintenance_equipment
from . import port_call
from . import disbursement_account
from . import account_move
from . import maintenance_part_line
from . import maintenance_request
from . import purchase_order
from . import purchase_order_line
from . import stock_picking
from . import control_center_dashboard
